apiVersion: v1
kind: Pod
metadata:
  name: interceptorpod
spec:
  containers:
    - name: javaconsumer
      image: charans97/interceptor:v2
      env:
       - name: Properties_file
         value: /etc/foo/interceptor.properties
      volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: true
  volumes:
    - name: foo
      configMap:
        name: intmap
